services:
  db:
    image: postgres:16-alpine
    container_name: postgres_portfolio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyStrongPass123
      POSTGRES_DB: PortfolioDb
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata: